export const DEFAULT_CONFIG = {
  agentTimeoutMs: 240000,
  synthesisTimeoutMs: 180000,
  defaultMaxRounds: 3,
  minRounds: 2,
  fastPathModel: "",
  embeddingModel: "Snowflake/snowflake-arctic-embed-xs",
  embeddingQuant: "onnx/model_int8.onnx",
  maxSummonsPerRound: 2,
  maxSummonsPerAgent: 1,
  moderatorTrigger: { minContributions: 3, recentChallenges: 2, lookbackWindow: 4 },
  maxRetryAttempts: 2,
  retryBaseDelayMs: 1000,
  retryMaxDelayMs: 8000,
  synthesisMaxRetries: 1,
  defaultMeetingTimeoutMs: 0,
  stallTimeoutMs: 600000,
  maxTotalTokens: 0,
  dashboard: { host: "127.0.0.1" },
  composition: { maxCosineDistance: 0.85 },
  circuitBreaker: {
    failureThreshold: 3,
    resetTimeoutMs: 300000,
  },
  modelFallback: {
    enabled: true,
    maxRetriesPerModel: 2,
    maxFallbackAttempts: 1,
  },
  agentTools: {
    enabled: true,
    builtIn: {
      webfetch: true,
      websearch: true,
      read: true,
      bash: {
        enabled: true,
        allowlist: ["git", "ls", "wc", "head", "tail", "grep", "find"],
      },
      glob: true,
      grep: true,
      lsp: false,
    },
    loom: {
      loom_vector_search: true,
      loom_query: true,
      loom_vote: true,
      loom_summon: true,
      loom_request_next: true,
    },
    sameTurnSynthesis: true,
    reflection: {
      bash: false,
      glob: false,
      grep: false,
    },
    maxToolCallsPerTurn: 8,
    maxToolOutputTokens: 6000,
  },
};

export const CONFIG_SCHEMA = {
  agentTimeoutMs: { type: 'number', min: 10000, max: 600000 },
  synthesisTimeoutMs: { type: 'number', min: 10000, max: 600000 },
  defaultMaxRounds: { type: 'number', min: 1, max: 10 },
  minRounds: { type: 'number', min: 1, max: 5 },
  fastPathModel: { type: 'string' },
  embeddingModel: { type: 'string' },
  embeddingQuant: { type: 'string' },
  maxRetryAttempts: { type: 'number', min: 0, max: 5 },
  retryBaseDelayMs: { type: 'number', min: 100, max: 30000 },
  retryMaxDelayMs: { type: 'number', min: 1000, max: 60000 },
  defaultMeetingTimeoutMs: { type: 'number', min: 0, max: 3600000 },
  stallTimeoutMs: { type: 'number', min: 30000, max: 1800000 },
  maxTotalTokens: { type: 'number', min: 0, max: 100000000 },
  maxSummonsPerRound: { type: 'number', min: 0, max: 5 },
  maxSummonsPerAgent: { type: 'number', min: 0, max: 3 },
  synthesisMaxRetries: { type: 'number', min: 0, max: 5 },
};

export const NESTED_SCHEMA = {
  'moderatorTrigger.minContributions': { type: 'number', min: 1, max: 10 },
  'moderatorTrigger.recentChallenges': { type: 'number', min: 1, max: 10 },
  'moderatorTrigger.lookbackWindow': { type: 'number', min: 2, max: 10 },
  'dashboard.host': { type: 'string' },
  'composition.maxCosineDistance': { type: 'number', min: 0.1, max: 1.9 },
  'circuitBreaker.failureThreshold': { type: 'number', min: 1, max: 10 },
  'circuitBreaker.resetTimeoutMs': { type: 'number', min: 10000, max: 3600000 },
  'agentTools.enabled': { type: 'boolean' },
  'agentTools.builtIn.webfetch': { type: 'boolean' },
  'agentTools.builtIn.websearch': { type: 'boolean' },
  'agentTools.builtIn.web_fetch': { type: 'boolean' },
  'agentTools.builtIn.web_search': { type: 'boolean' },
  'agentTools.builtIn.read': { type: 'boolean' },
  'agentTools.builtIn.bash.enabled': { type: 'boolean' },
  'agentTools.builtIn.glob': { type: 'boolean' },
  'agentTools.builtIn.grep': { type: 'boolean' },
  'agentTools.builtIn.lsp': { type: 'boolean' },
  'agentTools.loom.loom_vector_search': { type: 'boolean' },
  'agentTools.loom.loom_query': { type: 'boolean' },
  'agentTools.loom.loom_vote': { type: 'boolean' },
  'agentTools.loom.loom_summon': { type: 'boolean' },
  'agentTools.loom.loom_request_next': { type: 'boolean' },
  'agentTools.sameTurnSynthesis': { type: 'boolean' },
  'agentTools.reflection.bash': { type: 'boolean' },
  'agentTools.reflection.glob': { type: 'boolean' },
  'agentTools.reflection.grep': { type: 'boolean' },
  'agentTools.maxToolCallsPerTurn': { type: 'number', min: 1, max: 20 },
  'agentTools.maxToolOutputTokens': { type: 'number', min: 1000, max: 20000 },
  'modelFallback.enabled': { type: 'boolean' },
  'modelFallback.maxRetriesPerModel': { type: 'number', min: 0, max: 5 },
  'modelFallback.maxFallbackAttempts': { type: 'number', min: 0, max: 3 },
};

export const DEPRECATED_KEYS = {
  maxTurnRequestWords: 'never enforced — turn-request length is governed by prompts; key removed',
  maxTurnRequestsPerRound: 'never enforced — ordering is planTurnOrder; key removed',
  'turnRequestThresholds.autoGrant': 'dormant by design — ordering is planTurnOrder, not autoGrant; key removed',
  'agentTools.loom.loom_evidence': 'merged into loom_query with mode evidence — use loom_query with mode evidence instead',
  'agentTools.loom.loom_type': 'removed — primary agent turns are no longer typed, following agents interpret content directly',
};
